### ISSUE TITLE
Folder name does not have the same name as the repository

### ISSUE THREAD

**Issue by vongoh** [wppusher/wppusher-documentation#10]
I'm evaluating WP Pusher as a way to keep a live site synced with code changes I make on my localhost.  
I make custom themes and as a part of builds I use a plugin called Genesis Extender.  This plugin holds a lot of the functionality that builds the layouts of pages and more, so it is an essential part of every site I do.

That means my Git repos are all set up in the 'wp-content' directory - so that my commits always include both the theme directory under the contents of wp-content/themes/[THEME DIR] , as well as all the Extender code under wp-content/plugins/genesis-extender.

I'm at the Install New Theme screen in WPP, and the checkbox for 'Link Installed theme is telling me that the folder name must have the same name as my repository.   Does this mean that the plugin will not work with my architecture?  Thanks

**Comment by petersuhm** [comment]
It sounds like you need to use the Subdirectory option. WP Pusher should definitely be able to work for that specific use case.

Could you please email support@wppusher.com if you need more help with this? I'm much more responsive there 😄 . Thanks!
