### ISSUE TITLE
Error when activating the plugin

### ISSUE THREAD

**Issue by rafalfaro18** [wppusher/wppusher-documentation#12]
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /home4/solonaci/public_html/wp-content/plugins/wppusher/wppusher.php on line 20

**Comment by rafalfaro18** [comment]
Deleting the plugin from wordpress also doesn't work it freezes

**Comment by rafalfaro18** [comment]
Wordpress 4.6.1 
cPanel	2.2.31
Apache	2.2.31
PHP	5.6.27
MySQL	5.6.32

**Comment by petersuhm** [comment]
Hi there,

This error sounds very much like a PHP 5.2 version. It's a `use` statement it cannot parse. Can you please confirm that apache is using PHP 5.6 and not an old binary?

If you're still having issue, please send an email to peter@wppusher.com
