### ISSUE TITLE
Push to deploy - slashes

### ISSUE THREAD

**Issue by markhowellsmead** [wppusher/wppusher-documentation#13]
You state in the push-to-deploy information that _Adding a slash will solve the issue in most cases_ if the web server redirects to a path with a slash. But editing the **WordPress Address** or **Site Address** to include the slash isn't possible: WordPress removes the trailing slash when saving.

Do you have a more specific recommendation on how to handle this?

**Comment by petersuhm** [comment]
Hi Mark,

If a redirect is your issue, you will need to solve the issue on the WordPress installation / server or change the webhook on GitHub. You can test this by either looking at the GitHub debug information or by looking in the network tools in your browser when hitting the Push-to-Deploy URL reported by WP Pusher. If that URL is redirected to a path with, or without, a slash, that is incompatible with GitHub. At its core, it's a mis-configuration of WordPress on the server, but if you're unable to solve the issue, you will need to change the webhook so it's not redirected :)

I'm sorry if this is unclear from the docs. I'm working on a new version of the docs that are both more comprehensive and hopefully easier to follow!

**Comment by markhowellsmead** [comment]
Thanks @petersuhm. The issue is a general one and will apply to any WordPress installation using permalinks. I've since found that the issue only occurs with Bitbucket; setting up an identical plugin and repo. at Github doesn't have any issues. (The webhook URL is correctly defined with the trailing slash.)

**Comment by petersuhm** [comment]
I don't think permalinks should have anything to do with it in this case, unless something is not set up correctly in .htaccess... It's strange if it's not the same on GitHub and Bitbucket, as it's the same code generating the URL. Anyways, you can change the webhook URL on GitHub/Bitbucket if you get the redirect and it should work! :) Otherwise, let me know!

**Comment by markhowellsmead** [comment]
Thanks @petersuhm.
