### ISSUE TITLE
License not working

### ISSUE THREAD

**Issue by zu** [wppusher/wppusher-documentation#4]
I deactivated and unistalled the plugin and wanted it to reinstall but now it sais: This license key has reach the maximum amount of installations limit.
Where can I deactivate the not used license?

**Comment by petersuhm** [comment]
Hi @zu,

The license is not revoked when the plugin is deleted (which it should be and will be soon). I have deactivated the license for you so you can use it on another install.

I apologise for the inconvenience!

**Comment by zu** [comment]
it's ok and that was VERY quick! Thanks a lot
