### ISSUE TITLE
Notice being fired on development servers

### ISSUE THREAD

**Issue by cjmaio** [wppusher/wppusher-documentation#7]
The following notice is being shown on servers that show notices (e.g. our development server)

```
Notice: Undefined index: wppusher/wppusher.php in /var/www/wp-content/plugins/wppusher/wp-updates-plugin.php on line 32
```

Assuming it's a fairly easy fix, though. Environment if of interest:

PHP7
nginx + php7.0-fpm
Ubuntu 14.04

**Comment by petersuhm** [comment]
Thanks a lot for reporting this! I'll try to have it fix in the next release! :)
